

[context.production]
  command = "npm run build" # Prodüksiyon ortamı için kullanılacak komut.



[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  functions = "functions" # Netlify Functions'ların bulunduğu klasörü belirtin

[build.environment]
  
  MY_API_KEY = "E6VCGsgk5LLeTrNnPjX80W9obzXeQ1Tla7rrAJ3CLsTXiXllDBuroEJJYvXTocj9"
  DB_CONNECTION_STRING = "mongodb+srv://semainal:semainal@cluster0.fk5w3rx.mongodb.net/bookApp"




[build]
  command = "npm run build"
  publish = "build"
