[build]
  base = "build" # build klasörünü kullan
  publish = "build" # build klasörünü yayınla
  command = "npm run build" # Derleme komutu (gerektiğinde bu komutu değiştirin)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


