

[[redirects]]
from = "/*"
to = "/index.html"
status = 200



[build.environment]
  
  MY_API_KEY = "E6VCGsgk5LLeTrNnPjX80W9obzXeQ1Tla7rrAJ3CLsTXiXllDBuroEJJYvXTocj9"
  DB_CONNECTION_STRING = "mongodb+srv://semainal:semainal@cluster0.fk5w3rx.mongodb.net/bookApp"
  NODE_VERSION ="18"




[build]
  command = "npm run build"
  publish = "build"

  [functions]
  directory = "netlify/functions"
