# netlify.toml

# Build settings
[build]
  base = "public"  # Oluşturulan dosyaların bulunduğu klasör
  publish = "public"  # Oluşturulan dosyaların dağıtılacağı klasör
  command = "npm run build"  # Yapılandırma komutu (örneğin: npm veya yarn)

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Rewrite rules
[[redirects]]
  from = "/old-path/*"
  to = "/new-path/:splat"
  status = 301

# Asset optimization
[build.processing]
  # Add asset optimization settings here, if needed


