# Build sürecini yapılandırma
[build]
  command = "npm build"  # Projenizin derlenmesi için kullanılacak komut
  publish = "client"        # Derlenen dosyaların bulunduğu klasör

# Rewrites ve yönlendirmeleri yapılandırma
[[redirects]]
  from = "/*"             # Yönlendirme yapılacak URL deseni
  to = "/index.html"      # Yönlendirilen hedef URL

# Parola koruması ekleme
[[headers]]
  for = "/*"              # Parola korumasının uygulanacağı URL deseni
  [headers.values]
    Basic-Auth = "username:password"  # Parola koruması için kullanıcı adı ve şifre


