[build]
  command = "npm run build" # Projenin derleme komutu
  publish = "dist"         # Derleme sonuçlarının bulunduğu klasör

[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"

