[build]
  functions = "functions" # Netlify Functions'ların bulunduğu klasörü belirtin

[build.environment]
  
  MY_API_KEY = "E6VCGsgk5LLeTrNnPjX80W9obzXeQ1Tla7rrAJ3CLsTXiXllDBuroEJJYvXTocj9"
  DB_CONNECTION_STRING = "mongodb+srv://semainal:semainal@cluster0.fk5w3rx.mongodb.net/bookApp"

[context.production]
  command = "npm run build" 

[context.deploy-preview]
  command = "npm run build" 
