[[redirects]]
  from = "/auth/*"  # API istekleri için yol
  to = "https://master--bookdiaryapp.netlify.app/auth/:splat"  # API sunucusunun adresi, :splat dinamik parametre olarak kullanılabilir
  status = 200  # 200 OK yanıtı verilir

